# Generated by Django 4.1.5 on 2023-05-29 08:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserToken',
            new_name='UserApiKey',
        ),
        migrations.RenameField(
            model_name='userapikey',
            old_name='token',
            new_name='key',
        ),
    ]
