# Generated by Django 4.1.5 on 2023-06-26 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('completions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completion',
            name='content',
        ),
        migrations.AddField(
            model_name='completion',
            name='context_length_exceeded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='completion',
            name='error',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='completion',
            name='error_code',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='completion',
            name='message',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
