# Generated by Django 4.1.5 on 2023-06-27 17:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('completions', '0002_remove_completion_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completion',
            name='completer_id',
        ),
        migrations.RemoveField(
            model_name='completion',
            name='completer_type',
        ),
        migrations.AddField(
            model_name='completion',
            name='use_case',
            field=models.CharField(default='coder_completion', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='completion',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
