# Generated by Django 4.1.5 on 2023-05-08 12:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tasks', models.JSONField()),
                ('current_task_index', models.IntegerField()),
                ('files_changed', models.JSONField(default=dict)),
                ('requirements', models.CharField(max_length=2000)),
                ('context', models.CharField(max_length=2000)),
                ('complete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
