# Generated by Django 4.1.5 on 2023-05-11 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coder',
            name='running',
            field=models.BooleanField(default=False),
        ),
    ]
