# Generated by Django 4.1.5 on 2023-05-21 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coder', '0003_parsedresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='coder',
            name='reached_max_length',
            field=models.BooleanField(default=False),
        ),
    ]
