# Generated by Django 4.1.5 on 2023-05-22 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coder', '0004_coder_reached_max_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coder',
            name='running',
        ),
        migrations.AddField(
            model_name='coder',
            name='running_at',
            field=models.DateTimeField(null=True),
        ),
    ]
