# Generated by Django 4.1.5 on 2023-06-26 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coder', '0008_coder_error_codermessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codermessage',
            name='function_call',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
