# Generated by Django 4.1.5 on 2023-06-27 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coder', '0009_alter_codermessage_function_call'),
    ]

    operations = [
        migrations.AddField(
            model_name='coder',
            name='recipe',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
