# Generated by Django 4.1.5 on 2023-06-28 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coder', '0011_codermessage_system_command'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coder',
            name='recipe',
            field=models.CharField(default='gpt-4-0613', max_length=50),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CoderRecipe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('config', models.JSONField()),
                ('recipe', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'coder_recipes',
                'unique_together': {('user_id', 'recipe')},
            },
        ),
    ]
